apiVersion: v1
kind: Service
metadata:
  name: srv-loadb-superset
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8088
      targetPort: 8088
  selector:
    app: superset
    